/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as AccountsRouteImport } from './../routes/accounts'
import { Route as DashboardRouteImport } from './../routes/dashboard'
import { Route as PlaybookRouteImport } from './../routes/playbook'
import { Route as UseCasesRouteImport } from './../routes/use-cases'
import { Route as AccountsIndexRouteImport } from './../routes/accounts.index'
import { Route as AccountsAccountIdRouteImport } from './../routes/accounts.$accountId'
import { Route as UseCasesIdRouteImport } from './../routes/use-cases.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybookRoute = PlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesRoute = UseCasesRouteImport.update({
  id: '/use-cases',
  path: '/use-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsIndexRoute = AccountsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountsRoute,
} as any)
const AccountsAccountIdRoute = AccountsAccountIdRouteImport.update({
  id: '/$accountId',
  path: '/$accountId',
  getParentRoute: () => AccountsRoute,
} as any)
const UseCasesIdRoute = UseCasesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => UseCasesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/playbook': typeof PlaybookRoute
  '/use-cases': typeof UseCasesRouteWithChildren
  '/accounts/$accountId': typeof AccountsAccountIdRoute
  '/use-cases/$id': typeof UseCasesIdRoute
  '/accounts/': typeof AccountsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/playbook': typeof PlaybookRoute
  '/use-cases': typeof UseCasesRouteWithChildren
  '/accounts/$accountId': typeof AccountsAccountIdRoute
  '/use-cases/$id': typeof UseCasesIdRoute
  '/accounts': typeof AccountsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/playbook': typeof PlaybookRoute
  '/use-cases': typeof UseCasesRouteWithChildren
  '/accounts/$accountId': typeof AccountsAccountIdRoute
  '/use-cases/$id': typeof UseCasesIdRoute
  '/accounts/': typeof AccountsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/dashboard'
    | '/playbook'
    | '/use-cases'
    | '/accounts/$accountId'
    | '/use-cases/$id'
    | '/accounts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/playbook'
    | '/use-cases'
    | '/accounts/$accountId'
    | '/use-cases/$id'
    | '/accounts'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/dashboard'
    | '/playbook'
    | '/use-cases'
    | '/accounts/$accountId'
    | '/use-cases/$id'
    | '/accounts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  PlaybookRoute: typeof PlaybookRoute
  UseCasesRoute: typeof UseCasesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook': {
      id: '/playbook'
      path: '/playbook'
      fullPath: '/playbook'
      preLoaderRoute: typeof PlaybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases': {
      id: '/use-cases'
      path: '/use-cases'
      fullPath: '/use-cases'
      preLoaderRoute: typeof UseCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/': {
      id: '/accounts/'
      path: '/'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AccountsIndexRouteImport
      parentRoute: typeof AccountsRoute
    }
    '/accounts/$accountId': {
      id: '/accounts/$accountId'
      path: '/$accountId'
      fullPath: '/accounts/$accountId'
      preLoaderRoute: typeof AccountsAccountIdRouteImport
      parentRoute: typeof AccountsRoute
    }
    '/use-cases/$id': {
      id: '/use-cases/$id'
      path: '/$id'
      fullPath: '/use-cases/$id'
      preLoaderRoute: typeof UseCasesIdRouteImport
      parentRoute: typeof UseCasesRoute
    }
  }
}

interface AccountsRouteChildren {
  AccountsAccountIdRoute: typeof AccountsAccountIdRoute
  AccountsIndexRoute: typeof AccountsIndexRoute
}

const AccountsRouteChildren: AccountsRouteChildren = {
  AccountsAccountIdRoute: AccountsAccountIdRoute,
  AccountsIndexRoute: AccountsIndexRoute,
}

const AccountsRouteWithChildren = AccountsRoute._addFileChildren(
  AccountsRouteChildren,
)

interface UseCasesRouteChildren {
  UseCasesIdRoute: typeof UseCasesIdRoute
}

const UseCasesRouteChildren: UseCasesRouteChildren = {
  UseCasesIdRoute: UseCasesIdRoute,
}

const UseCasesRouteWithChildren = UseCasesRoute._addFileChildren(
  UseCasesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRouteWithChildren,
  DashboardRoute: DashboardRoute,
  PlaybookRoute: PlaybookRoute,
  UseCasesRoute: UseCasesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
